name: bogo_city_sos
description: "A simple Emergency SOS Flutter App for Bogo City"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.0
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1  # <-- Gi-dugang para sa App Icon

flutter:
  uses-material-design: true

  # Gi-declare ang folder diin nahimutang ang imong icon
  assets:
    - assets/icon/

# Configuration settings para sa pag-build sa App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21